name: CD. AWS Lightsail
on:
  push:
    branches:
      - master

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on AWS Lightsail
    runs-on: ubuntu-22.04

    steps:
      - name: ‚¨áÔ∏è Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ‚öôÔ∏è Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: üì¶ Install dependencies
        run: npm ci

      - name: üè∑Ô∏è Get version from package.json
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV
          echo "PACKAGE_PATH=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV

      - name: üèóÔ∏è Build Angular app
        run: npm run build-prod

      - name: ‚òÅÔ∏è Upload build to AWS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER }}
          port: 22 # SSH
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY }}
          source: "dist/goa-front/**"
          target: "~/goa-front-temp"

      - name: üöÄ Deploy frontend on Nginx (AWS Lightsail)
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER }}
          port: 22
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/goa-front
            sudo rm -rf /var/www/goa-front/*
            sudo cp -r ~/goa-front-temp/dist/goa-front/browser/* /var/www/goa-front/
            sudo rm -rf ~/goa-front-temp
            sudo systemctl reload nginx
